FROM node:alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci --omit=dev && \
    npm install pm2 && \
    npm cache clean --force

COPY . .

EXPOSE 3000

RUN ["pm2", "start", "server.js"]